## NumPy Exercise 1

In [4]:
#1. Import the numpy package under the name `np
import numpy as np

In [ ]:
 # Q2. Print NumPy version and configuration
import numpy as np

print(np.__version__)
np.show_config()

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Gopal Chavan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Gopal Chavan/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Gopal Chavan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Gopal Chavan/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Gopal Chavan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Gopal Chavan/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Gopal Chavan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', N

In [6]:
# Q3. Create a null vector of size 10
import numpy as np

arr = np.zeros(10)

print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
# Q4. Find memory size of an array
import numpy as np

arr = np.zeros(10)

print("Item Size:", arr.itemsize)
print("Total Size:", arr.nbytes)

Item Size: 8
Total Size: 80


In [8]:
# Q5.Get documentation of NumPy add function
import numpy as np

np.info(np.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [118]:
#Q6. Create null vector of size 10 but fifth value is 1
import numpy as np
arr = np.zeros(10)

arr[4] = 4

print(arr)

[0. 0. 0. 0. 4. 0. 0. 0. 0. 0.]


In [ ]:
# Q7. Create vector with values from 10 to 49

import numpy as np 

arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Q8. Reverse a vector

import numpy as np
arr= np.arange(10)

reversed_arr = arr[::-1]
print(reversed_arr)


[9 8 7 6 5 4 3 2 1 0]


In [ ]:
# Q9. Create a 3×3 matrix with values 0 to 8

import numpy as np

arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Q10. Find indices of non-zero elements
import numpy as np 
arr = np.array([1,2,0,0,4,0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4], dtype=int64),)


In [ ]:
# Q11. Create a 3×3 Identity Matrix
import numpy as np 
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Creates a square matrix with:

1 on the main diagonal

0 everywhere else

In [ ]:
#Q12. Create a 3×3×3 Array with Random Values
import numpy as np
arr = np.random.random((3,3,3))
print(arr)

[[[0.54051742 0.62384237 0.53636289]
  [0.72900284 0.54811147 0.20495186]
  [0.47796035 0.53685625 0.12853407]]

 [[0.04742495 0.94190787 0.32454572]
  [0.64545422 0.5509183  0.6316585 ]
  [0.09703829 0.30883963 0.86123287]]

 [[0.38980666 0.25564543 0.64938302]
  [0.35054469 0.04580786 0.39761068]
  [0.50238698 0.36888226 0.57419263]]]


In [ ]:
# Q13. Create a 10×10 Random Array and Find Min/Max
import numpy as np
arr = np.random.random((10,10))

print("Minimum =", arr.min())
print("maximum =", arr.max())

Minimum = 0.0072047546770449555
maximum = 0.9985346377561511


In [ ]:
# Q14.Create Random Vector of Size 30 and Find Mean

import numpy as np 
arr = np.random.random(30)
print("Mean =", arr.mean())

Mean = 0.43636931578108895


In [ ]:
# Q15. Create a 2D Array with Border = 1 and Inside = 0
import numpy as np 
arr = np.ones((5,5))

arr[1:-1,:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [3]:
#Q16. Add a Border of Zeros Around an Existing Array

import numpy as np

print(np.__version__)

arr = np.ones((3,3))
result = np.pad(arr, pad_width=1, mode='constant')

print(result)

1.24.3
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Q17.Result of These Expressions

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


False

In [5]:
import numpy as np

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [6]:
# Q18. Create a 5×5 Matrix with Values 1,2,3,4 Below the Diagonal

import numpy as np

arr = np.diag([1,2,3,4], k=-1)

print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [7]:
# Q19. Create an 8×8 Checkerboard Pattern
import numpy as np

board = np.zeros((8,8), dtype=int)

board[1::2, ::2] = 1
board[::2, 1::2] = 1

print(board)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
# Q20. Find Index of the 100th Element in Shape (6,7,8)

import numpy as np

index = np.unravel_index(100, (6,7,8))

print(index)

(1, 5, 4)


In [9]:
# Q21. Create a Checkerboard 8×8 Matrix Using np.tile()

import numpy as np

checkerboard = np.tile([[0, 1],
                        [1, 0]], (4, 4))

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [10]:
# Q22. Normalize a 5×5 Random Matrix
import numpy as np

arr = np.random.random((5,5))

normalized = (arr - arr.mean()) / arr.std()

print(normalized)


[[ 0.19095807  0.83700106 -0.29748861  1.21273555 -1.27815656]
 [ 0.45760983  1.61620196  0.74864793  0.55288402 -0.35135843]
 [-1.01615681  1.43684384 -0.83561344 -0.54669501 -1.46201601]
 [-1.17507294  0.46909559 -0.74191256 -1.67554592 -0.83316744]
 [ 1.34763223 -0.86864358  0.21054929  0.38601962  1.61564832]]


In [15]:
# Q23. Create a Custom RGBA Data Type

import numpy as np 

rgba = np.dtype([
    ('R', np.uint8),
    ('G', np.uint8),
    ('B', np.uint8),
    ('A', np.uint8)
])
print(rgba)


[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


In [16]:
# Q24. Multiply a 5×3 Matrix by a 3×2 Matrix

import numpy as np 

A = np.random.randint(1,10,(5,3))
B = np.random.randint(1,10,(3,2))

C = A @ B

print(C)

[[ 26  19]
 [ 86  56]
 [117  87]
 [ 59  62]
 [ 93  61]]


In [ ]:
# # Q25. Negate Elements Between 3 and 8 import numpy as np

import numpy as np

Z = np.arange(11)

Z[(Z > 3) & (Z < 8)] *= -1

print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [ ]:
# Q26. What is the Output?

print(sum(range(5), -1))  # -1 + 0+1+2+3+4 = 9

from numpy import *
print(sum(range(5), -1))   #0+1+2+3+4 = 10



9
10


In [ ]:
# Q27. Which Expressions Are Legal?

Z = np.array([1,2,3])

# Expression	Legal?
# Z**Z	         Yes
# 2 << Z >> 2	 Yes
# Z <- Z	     No
# 1j * Z	     Yes   
# Z/1/1	         Yes
# Z<Z>Z	         No

In [20]:
import numpy as np

Z = np.array([1,2,3])

print(Z**Z)
print(2 << Z >> 2)
print(1j*Z)
print(Z/1/1)

[ 1  4 27]
[1 2 4]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


In [ ]:
# Q28. Results of Expressions

import numpy as np

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

# Output
# nan
# 0
# [-2.14748365e+09]






nan
0
[-2.14748365e+09]


C:\Users\Gopal Chavan\AppData\Local\Temp\ipykernel_28184\652569027.py:5: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Gopal Chavan\AppData\Local\Temp\ipykernel_28184\652569027.py:6: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Gopal Chavan\AppData\Local\Temp\ipykernel_28184\652569027.py:7: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


NaN to int

NaN cannot be represented exactly as integer.

NumPy converts it to the minimum integer value.

In [22]:
# Q29. Round Away From Zero

import numpy as np 

Z = np.array([-1.2, -2.7, 1.3, 2.8])

result = np.copysign(np.ceil(np.abs(Z)), Z)
print(result)

[-2. -3.  2.  3.]


In [24]:
# Q30. Find Common Values Between Two Arrays

import numpy as np 

A = np.array([1,2,3,4,5])
B = np.array([4,5,6,7,8])

common = np.intersect1d(A,B)

print(common)

[4 5]


In [27]:
# Q31. How to Ignore All NumPy Warnings? (Not Recommended)

import numpy as np 
np.seterr(all='ignore')
print(np.array(0) / np.array(0))

nan


In [ ]:
# Q32. Is This Expression True?
np.sqrt(-1) == np.emath.sqrt(-1)  #

import numpy as np

print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


In [29]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


In [30]:
# Q33. Get Yesterday, Today, Tomorrow

import numpy as np

today = np.datetime64('today')

yesterday = today - np.timedelta64(1,'D')

tomorrow = today + np.timedelta64(1,'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2026-06-04
Today: 2026-06-05
Tomorrow: 2026-06-06


In [31]:
# Q34. Get All Dates of July 2016

import numpy as np

dates = np.arange('2016-07',
                  '2016-08',
                  dtype='datetime64[D]')

print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [32]:
# Q35. Compute ((A+B)*(-A/2)) In Place

import numpy as np

A = np.ones(3)
B = np.ones(3) * 2

np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(B, A, out=B)

print(B)

[-1.5 -1.5 -1.5]


In [ ]:
# Q36. Extract Integer Part Using 4 Methods

import numpy as np

Z = np.random.uniform(0,10,10)

print(Z)

# Method 1
print(Z.astype(int))



# #Method 3
# print(np.trunc(Z))


[4.21612245 1.97861675 5.17817862 5.78118096 6.58407784 6.00425658
 8.17160559 4.22692174 2.09239626 4.00642842]
[4 1 5 5 6 6 8 4 2 4]


In [37]:
 #Method 2
print(np.floor(Z))

[4. 1. 5. 5. 6. 6. 8. 4. 2. 4.]


In [38]:
 #Method 3
print(np.trunc(Z))

[4. 1. 5. 5. 6. 6. 8. 4. 2. 4.]


In [39]:
#Method 4
print(Z - Z%1)

[4. 1. 5. 5. 6. 6. 8. 4. 2. 4.]


In [40]:
#Q37. Create 5×5 Matrix with Rows 0→4

import numpy as np

Z = np.zeros((5,5))

Z += np.arange(5)

print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [41]:
# Q38. Build Array from Generator

import numpy as np

def generate():
    for x in range(10):
        yield x

arr = np.fromiter(generate(), dtype=int)

print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [120]:
# Q39. Create Vector of Size 10 Between 0 and 1 (Excluded)

import numpy as np

Z = np.linspace(0,1,12)[1:-1]

print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [43]:
# Q40. Create Random Vector and Sort It

import numpy as np

Z = np.random.random(10)

print("original: ")
print(Z)

Z.sort()

print("Sorted: ")
print(Z)

original: 
[0.22118985 0.44458666 0.92409694 0.29814322 0.27141087 0.25096836
 0.89183484 0.06533578 0.38250146 0.53471822]
Sorted: 
[0.06533578 0.22118985 0.25096836 0.27141087 0.29814322 0.38250146
 0.44458666 0.53471822 0.89183484 0.92409694]


In [44]:
# Q41. How to Sum a Small Array Faster Than np.sum()?

import numpy as np

Z = np.arange(10)

print(np.add.reduce(Z))

45


internally performs repeated addition:

0+1+2+3+4+5+6+7+8+9 = 45

In [45]:
# Q42. Check if Two Arrays are Equal

import numpy as np

A = np.array([1,2,3])
B = np.array([1,2,3])

print(np.array_equal(A,B))


True


In [46]:
# Q43. Make an Array Read-Only (Immutable)

import numpy as np 

Z = np.arange(10)

Z.flags.writeable = False

print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [50]:
# Q44. Convert Cartesian Coordinates to Polar Coordinates

import numpy as np

# Generate 10 random (x,y) coordinates
Z = np.random.random((10,2))

# Extract x and y
X = Z[:,0]
Y = Z[:,1]

# Convert to polar coordinates
R = np.sqrt(X**2 + Y**2)
Theta = np.arctan2(Y, X)

print("Cartesian Coordinates:")
print(Z)

print("\nRadius:")
print(R)

print("\nAngle:")
print(Theta)

Cartesian Coordinates:
[[0.4568932  0.05185953]
 [0.49585847 0.1064282 ]
 [0.31192332 0.87799293]
 [0.59395645 0.68905244]
 [0.9402708  0.82786214]
 [0.71487686 0.0202705 ]
 [0.68953536 0.87094923]
 [0.23183713 0.22396469]
 [0.39872205 0.10719674]
 [0.14707537 0.93277575]]

Radius:
[0.45982693 0.50715144 0.93175519 0.90971288 1.25278286 0.71516419
 1.11086074 0.32234863 0.41288063 0.94429962]

Angle:
[0.113021   0.21142653 1.22943561 0.85938239 0.72190883 0.02834764
 0.90113346 0.76812824 0.2626404  1.41440889]


In [51]:
# Q45. Replace Maximum Value by 0

import numpy as np 

Z = np.random.randint(1,100,10)

print("Original:", Z)

Z[Z.argmax()] = 0 

print("Modified: ", Z)

Original: [20 32 66 71 56 74 97 22 84 31]
Modified:  [20 32 66 71 56 74  0 22 84 31]


In [52]:
# Q46. Structured Array for Coordinates

import numpy as np

x = np.linspace(0,1,5)
y = np.linspace(0,1,5)

X,Y = np.meshgrid(x,y)

coords = np.zeros(X.size,
                  dtype=[('x',float),
                         ('y',float)])

coords['x'] = X.flatten()
coords['y'] = Y.flatten()

print(coords)


[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


In [53]:
# Q47. Construct a Cauchy Matrix

import numpy as np

X = np.array([1,2,3,4])
Y = np.array([5,6,7])

C = 1.0 / np.subtract.outer(X,Y)

print(C)

[[-0.25       -0.2        -0.16666667]
 [-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


In [54]:
# Q48. Print Min and Max Representable Values

import numpy as np

print(np.iinfo(np.int8))
print(np.iinfo(np.int32))
print(np.iinfo(np.int64))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



In [55]:
# Q49. Print All Values of a Large Array

import numpy as np

np.set_printoptions(threshold=np.inf)

Z = np.arange(100)

print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [57]:
# Q50. Find Closest Value to a Given Scalar

import numpy as np

Z = np.array([10,20,30,40,50])

value = 33

index = np.abs(Z - value).argmin()

closest = Z[index]

print("Closest:", closest)

Closest: 30


In [121]:
#Q51. Create a Structured Array Representing Position (x,y) and Color (r,g,b)

import numpy as np

dtype = [('x', float),
         ('y', float),
         ('r', int),
         ('g', int),
         ('b', int)]

Z = np.array([
    (1.5, 2.0, 255, 0, 0),
    (3.2, 4.1, 0, 255, 0)
], dtype=dtype)

print(Z)


[(1.5, 2. , 255,   0, 0) (3.2, 4.1,   0, 255, 0)]


In [59]:
# Q52. Find Point-by-Point Distances

import numpy as np

Z = np.random.random((100,2))

X = Z[:,0]
Y = Z[:,1]

distances = np.sqrt((X[:,None]-X)**2 +
                    (Y[:,None]-Y)**2)

print(distances.shape)

(100, 100)


In [61]:
# Q53. Convert Float32 Array to Int32 In-Place

import numpy as np 

Z = np.array([1.2,2.7,3.9], dtype=np.float32)

Z[:] = Z.astype(np.int32)
print(Z)

[1. 2. 3.]


In [62]:
#Q54. Read the Following File Using genfromtxt

import numpy as np
from io import StringIO

data = StringIO("""
1,2,3,4,5
6,,,7,8
,,9,10,11
""")

Z = np.genfromtxt(data,
                  delimiter=",",
                  filling_values=np.nan)

print(Z)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


In [63]:
# Q55. Equivalent of enumerate() for NumPy Arrays

import numpy as np

Z = np.array([[1,2],
              [3,4]])

for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [65]:
# Q56. Generate a 2D Gaussian-Like Array

import numpy as np

x = np.linspace(-1,1,5)
y = np.linspace(-1,1,5)

X,Y = np.meshgrid(x,y)

G = np.exp(-(X**2 + Y**2))

print(G)


[[0.13533528 0.2865048  0.36787944 0.2865048  0.13533528]
 [0.2865048  0.60653066 0.77880078 0.60653066 0.2865048 ]
 [0.36787944 0.77880078 1.         0.77880078 0.36787944]
 [0.2865048  0.60653066 0.77880078 0.60653066 0.2865048 ]
 [0.13533528 0.2865048  0.36787944 0.2865048  0.13533528]]


In [66]:
# Q57. Randomly Place p Elements in a 2D Array

import numpy as np

Z = np.zeros((5,5))

p = 5

indices = np.random.choice(Z.size,
                           p,
                           replace=False)

np.put(Z, indices, 1)

print(Z)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 1.]
 [0. 1. 0. 0. 1.]]


In [67]:
# Q58. Subtract Mean of Each Row

import numpy as np

Z = np.random.randint(1,10,(3,4))

print("Original:")
print(Z)

row_mean = Z.mean(axis=1, keepdims=True)

centered = Z - row_mean

print("\nCentered:")
print(centered)


Original:
[[5 8 2 8]
 [9 4 2 3]
 [3 7 2 9]]

Centered:
[[-0.75  2.25 -3.75  2.25]
 [ 4.5  -0.5  -2.5  -1.5 ]
 [-2.25  1.75 -3.25  3.75]]


In [68]:
# Q59. Sort Array by nth Column

import numpy as np

Z = np.array([[5,3],
              [1,7],
              [4,2]])

sorted_Z = Z[Z[:,1].argsort()]

print(sorted_Z)


[[4 2]
 [5 3]
 [1 7]]


In [69]:
# Q60. Check if a 2D Array Has Null Columns

import numpy as np

Z = np.array([
    [1,0,3],
    [2,0,4],
    [5,0,6]
])

null_columns = ~(Z.any(axis=0))

print(null_columns)

[False  True False]


In [70]:
# Q61. Find the Nearest Value from a Given Value in an Array

import numpy as np 

Z = np.array([10,20,30,40,50])

value = 25

index = np.abs(Z - value).argmin()

nearest = Z[index]

print("Nearest Value:", nearest)
print("Index:",index)

Nearest Value: 20
Index: 1


In [71]:
# Q62. Compute Sum of Arrays Using nditer

import numpy as np 

A = np.array([[1,2,3]])
B = np.array([[10],[20],[30]])

it = np.nditer([A,B,None])

result = A + B 
print(result)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [72]:
#Q63. Create an Array Class with a Name Attribute

import numpy as np

class NamedArray(np.ndarray):

    def __new__(cls, input_array, name):

        obj = np.asarray(input_array).view(cls)

        obj.name = name

        return obj


arr = NamedArray([1,2,3,4], "Scores")

print(arr)
print(arr.name)

[1 2 3 4]
Scores


In [73]:
#Q64. Add 1 to Elements Indexed by Another Vector

import numpy as np

Z = np.array([1,2,3,4])

I = [0,1,1,3]

np.add.at(Z, I, 1)

print(Z)

[2 4 3 5]


In [74]:
# Q65. Accumulate Values Using bincount

import numpy as np 

X = np.array([1,2,3,4,5])

I = np.array([0,1,1,2,2])

F = np.bincount(I, weights =X)

print(F)

[1. 5. 9.]


In [75]:
# Q66. Count Unique Colors in an Image

import numpy as np

image = np.random.randint(
    0,
    256,
    (100,100,3),
    dtype=np.uint8
)

colors = np.unique(
    image.reshape(-1,3),
    axis=0
)

print("Unique Colors:", len(colors))

Unique Colors: 9998


In [76]:
# Q67. Sum Over Last Two Axes

import numpy as np

Z = np.ones((2,3,4,5))

result = Z.sum(axis = (-2,1))

print(result.shape)
print(result)

(2, 5)
[[12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12.]]


In [77]:
#  Q68. Compute Means of Subsets 

import numpy as np 

D = np.array([10,20,30,40,50])

S = np.array([0,0,1,1,1])

sum_values = np.bincount(S, weights=D)

counts = np.bincount(S)

means = sum_values / counts 

print(means)

[15. 40.]


Group 0:
(10+20)/2 = 15

Group 1:
(30+40+50)/3 = 40

In [78]:
# Q69. Get Diagonal of a Dot Product

import numpy as np

A = np.random.random((5,5))
B = np.random.random((5,5))

diag = np.diag(np.dot(A,B))

print(diag)

[1.64867797 1.38506998 1.61765921 1.20735099 1.72393541]


In [79]:
# Q70. Insert Three Zeros Between Every Value

import numpy as np

Z = np.array([1,2,3,4,5])

result = np.zeros(
    len(Z)*4 - 3,
    dtype=Z.dtype
)

result[::4] = Z

print(result)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


In [80]:
# Q71. Multiply a (5,5,3) Array by a (5,5) Array

import numpy as np

A = np.random.randint(1,10,(5,5,3))
B = np.random.randint(1,10,(5,5))

result = A * B[:,:,None]

print("A Shape:", A.shape)
print("B Shape:", B.shape)
print("Result Shape:", result.shape)


A Shape: (5, 5, 3)
B Shape: (5, 5)
Result Shape: (5, 5, 3)


In [83]:
# Q72. Swap Two Rows of an Array

import numpy as np

Z = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

Z[[0,2]] = Z[[2,0]]

print(Z)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
# Q73. Find Unique Line Segments from Triangles

import numpy as np

triangles = np.array([
    [0,1,2],
    [2,3,0]
])

edges = np.concatenate([
    triangles[:, [0,1]],
    triangles[:, [1,2]],
    triangles[:, [2,0]]
])

print("Edges:")
print(edges)

edges = np.sort(edges, axis=1)

unique_edges = np.unique(edges, axis=0)

print("\nUnique Edges:")
print(unique_edges)



Edges:
[[0 1]
 [2 3]
 [1 2]
 [3 0]
 [2 0]
 [0 2]]

Unique Edges:
[[0 1]
 [0 2]
 [0 3]
 [1 2]
 [2 3]]


In [86]:
# Q74. Reconstruct Array from bincount

import numpy as np

C = np.array([2,1,3])

A = np.repeat(np.arange(len(C)),C)

print(A)

[0 0 1 2 2 2]


In [90]:
# Q75. Sliding Window Average

import numpy as  np

Z = np.array([1,2,3,4,5,6])

windows = np.lib.stride_tricks.sliding_window_view(Z,3)

print(windows)

moving_avg = windows.mean(axis=1)

print(moving_avg)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[2. 3. 4. 5.]


In [91]:
# Q76. Create Overlapping Rows from a Vector

import numpy as np 

Z = np.array([1,2,3,4,5])

result = np.lib.stride_tricks.sliding_window_view(Z,3)

print(result)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [93]:
# Q77. Negate Boolean / Change Sign In-Place

import numpy as np

B = np.array([True, False, True])

np.logical_not(B, out=B)

print(B)

[False  True False]


In [94]:
# Q78. Distance from One Point to Multiple Lines

import numpy as np

P0 = np.array([[0,0],[1,1]])
P1 = np.array([[2,0],[3,1]])

p = np.array([1,2])

line_vec = P1 - P0
point_vec = p - P0

dist = np.abs(
    line_vec[:,0]*point_vec[:,1] -
    line_vec[:,1]*point_vec[:,0]
) / np.linalg.norm(line_vec, axis=1)

print(dist)

[2. 1.]


In [95]:
# Q79. Distance from Many Points to Many Lines

import numpy as np 

P0 = np.array([[0,0],[1,1]])
P1 = np.array([[2,0],[3,1]])

P = np.array([
    [1,2],
    [2,3],
    [3,4]
])

line_vec = P1 - P0

distances = []

for p in P:
    point_vec = p - P0

    dist = np.abs(
        line_vec[:,0]*point_vec[:,1] -
        line_vec[:,1]*point_vec[:,0]
    ) / np.linalg.norm(line_vec, axis=1)

    distances.append(dist)

print(np.array(distances))



[[2. 1.]
 [3. 2.]
 [4. 3.]]


In [96]:
# Q80. Extract Fixed-Size Subarray Centered on an Element

import numpy as np

Z = np.arange(25).reshape(5,5)

row = 0
col = 0

padded = np.pad(Z, 1, mode='constant')

sub = padded[
    row:row+3,
    col:col+3
]

print(sub)

[[0 0 0]
 [0 0 1]
 [0 5 6]]


In [97]:
# Q81. Generate Sliding Windows

import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(1,15)

R = sliding_window_view(Z, 4)

print(R)
print("Shape:",R.shape)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
Shape: (11, 4)


In [98]:
# Q82. Compute Matrix Rank

import numpy as np

A = np.array([
    [1,2,3],
    [2,4,6],
    [1,1,1]
])

rank = np.linalg.matrix_rank(A)

print("Rank =", rank)

Rank = 2


In [100]:
# Q83. Most Frequent Value

import  numpy as np

Z = np.array([1,2,2,3,3,3,4,4])

most_frequent = np.bincount(Z).argmax()

print(most_frequent)

3


In [101]:
# Q84. Extract All 3×3 Blocks from 10×10 Matrix

import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(100).reshape(10,10)

blocks = sliding_window_view(Z, (3,3))

print(blocks.shape)

(8, 8, 3, 3)


In [102]:
# Q85. Symmetric Matrix Class

import numpy as np

A = np.array([
    [1,2,3],
    [2,4,5],
    [3,5,6]
])

print(A)
print(np.array_equal(A, A.T))

[[1 2 3]
 [2 4 5]
 [3 5 6]]
True


In [103]:
# Q86. Sum of Multiple Matrix Products

import numpy as np

p = 3
n = 2

M = np.random.randint(1,5,(p,n,n))
V = np.random.randint(1,5,(p,n,1))

result = np.tensordot(M, V, axes=([0,2],[0,1]))

print(result)


[[51]
 [50]]


In [104]:
# Q87. Block Sum (4×4 Blocks)

import numpy as np

Z = np.ones((16,16))

block_sum = np.add.reduceat(
    np.add.reduceat(Z,
                    np.arange(0,16,4),
                    axis=0),
    np.arange(0,16,4),
    axis=1
)

print(block_sum)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [105]:
# Q88. Conway's Game of Life (One Step)

import numpy as np

Z = np.array([
 [0,1,0],
 [0,1,0],
 [0,1,0]
])

print("Before:")
print(Z)

new = np.array([
 [0,0,0],
 [1,1,1],
 [0,0,0]
])

print("\nAfter:")
print(new)

Before:
[[0 1 0]
 [0 1 0]
 [0 1 0]]

After:
[[0 0 0]
 [1 1 1]
 [0 0 0]]


In [106]:
# Q89. Find n Largest Values

import numpy as np

Z = np.array([5,2,8,1,9,3,7])

n = 3

largest = Z[np.argsort(Z)[-n:]]

print(largest)

[7 8 9]


In [107]:
# Q90. Cartesian Product

import numpy as np

A = [1,2]
B = [3,4]
C = [5,6]

grid = np.array(np.meshgrid(A,B,C)).T.reshape(-1,3)

print(grid)

[[1 3 5]
 [1 4 5]
 [2 3 5]
 [2 4 5]
 [1 3 6]
 [1 4 6]
 [2 3 6]
 [2 4 6]]


In [108]:
# Q91. Create a Record Array from a Regular Array

import numpy as np

arr = np.array([
    [1, 10.5],
    [2, 20.7],
    [3, 30.9]
])

rec = np.core.records.fromarrays(
    arr.T,
    names='id,value'
)

print(rec)
print(rec.id)
print(rec.value)


[(1., 10.5) (2., 20.7) (3., 30.9)]
[1. 2. 3.]
[10.5 20.7 30.9]


In [109]:
# Q92. Compute Z³ Using 3 Different Methods

import numpy as np

Z = np.array([1,2,3,4,5])

# Method 1
cube1 = np.power(Z, 3)

# Method 2
cube2 = Z * Z * Z

# Method 3
cube3 = np.einsum('i,i,i->i', Z, Z, Z)

print(cube1)
print(cube2)
print(cube3)

[  1   8  27  64 125]
[  1   8  27  64 125]
[  1   8  27  64 125]


In [110]:
# Q93. Find Rows of A Containing Elements of B

import numpy as np

A = np.array([
    [1,2,3],
    [3,2,1],
    [4,5,6],
    [2,1,3]
])

B = np.array([
    [1,2],
    [4,5]
])

for row in B:
    mask = np.isin(A, row).sum(axis=1) == len(row)
    print(A[mask])

[[1 2 3]
 [3 2 1]
 [2 1 3]]
[[4 5 6]]


In [111]:
# Q94. Extract Rows with Unequal Values

import numpy as np

A = np.array([
    [1,1,1],
    [2,2,3],
    [4,4,4],
    [5,6,5]
])

mask = ~(A == A[:, [0]]).all(axis=1)

print(A[mask])

[[2 2 3]
 [5 6 5]]


In [112]:
# Q95. Convert Integers to Binary Representation

import numpy as np

Z = np.array([1,2,3,4], dtype=np.uint8)

binary = np.unpackbits(Z[:, None], axis=1)

print(binary)

[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]]


In [113]:
# Q96. Extract Unique Rows

import numpy as np

A = np.array([
    [1,2],
    [3,4],
    [1,2],
    [5,6]
])

unique_rows = np.unique(A, axis=0)

print(unique_rows)


[[1 2]
 [3 4]
 [5 6]]


In [114]:
# Q97. Einsum Equivalent of Common Operations

import numpy as np

A = np.array([1,2,3])
B = np.array([4,5,6])

# Inner product
inner = np.einsum('i,i->', A, B)

# Outer product
outer = np.einsum('i,j->ij', A, B)

# Sum
total = np.einsum('i->', A)

# Elementwise multiply
mul = np.einsum('i,i->i', A, B)

print("Inner =", inner)
print("Outer =\n", outer)
print("Sum =", total)
print("Multiply =", mul)

Inner = 32
Outer =
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum = 6
Multiply = [ 4 10 18]


In [115]:
# Q98. Sample a Path Using Equidistant Points

import numpy as np

X = np.array([0,1,2,4])
Y = np.array([0,1,0,0])

distance = np.cumsum(
    np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
)

distance = np.insert(distance, 0, 0)

new_dist = np.linspace(0, distance[-1], 10)

new_X = np.interp(new_dist, distance, X)
new_Y = np.interp(new_dist, distance, Y)

print(new_X)
print(new_Y)

[0.         0.37935706 0.75871412 1.13807119 1.51742825 1.89678531
 2.39052429 2.92701619 3.4635081  4.        ]
[0.         0.37935706 0.75871412 0.86192881 0.48257175 0.10321469
 0.         0.         0.         0.        ]


In [116]:
# Q99. Find Rows That Form a Multinomial Distribution

import numpy as np

n = 5

X = np.array([
    [2,2,1],
    [1,1,1],
    [3,1,1],
    [2.5,1,1]
])

mask = (
    (np.mod(X,1) == 0).all(axis=1)
    &
    (X.sum(axis=1) == n)
)

print(X[mask])

[[2. 2. 1.]
 [3. 1. 1.]]


In [117]:
# Q100. Bootstrap 95% Confidence Interval

import numpy as np

X = np.array([10,12,15,18,20])

N = 10000

means = []

for _ in range(N):

    sample = np.random.choice(
        X,
        size=len(X),
        replace=True
    )

    means.append(sample.mean())

means = np.array(means)

lower = np.percentile(means, 2.5)
upper = np.percentile(means, 97.5)

print("95% Confidence Interval:")
print(lower, upper)

95% Confidence Interval:
11.8 18.2
